//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRestaurante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblRestaurante()
        {
            this.TblPratoes = new HashSet<TblPrato>();
        }
    
        public int IdRestaurante { get; set; }
        public string NomeRestaurante { get; set; }
        public Nullable<int> IdPrato { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPrato> TblPratoes { get; set; }
        public virtual TblPrato TblPrato { get; set; }
    }
}
